name: pydba
dependencies:
- ncurses=5.9=1
- openssl=1.0.1k=1
- pip=7.1.2=py27_0
- python=2.7.10=1
- readline=6.2.5=1
- setuptools=18.1=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.24.0=py27_0
- zlib=1.2.8=1
- pip:
  - psycopg2==2.6.1
